###############################################
# PLOTTER GUI #################################
# Wraps PlotterClass with a Tkinter interface #
# GENERATED BY: CLAUDE AI #####################
# TESTED AND UPDATED BY: ALEXANDER HEDRICK ####
# LAST UPDATED: 2026-04-28 ####################
###############################################

import tkinter as tk
from tkinter import ttk, filedialog, messagebox
import numpy as np
import pandas as pd
import os
import pickle
from scipy.io import loadmat
from scipy.interpolate import interp1d
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('TkAgg')

# -- Colour Palette ----------------------------------------------------------
BG        = "#0f1117"
PANEL     = "#1a1d27"
CARD      = "#21253a"
ACCENT    = "#11aaaf"
ACCENT2   = "#e05c8a"
TEXT      = "#e8eaf0"
TEXT_DIM  = "#7a7f99"
BORDER    = "#2e3452"
SUCCESS   = "#3ecf8e"
FONT_H    = ("Courier New", 13, "bold")
FONT_B    = ("Courier New", 11)
FONT_S    = ("Courier New", 10)
FONT_L    = ("Courier New", 14, "bold")
FONT_XL   = ("Courier New", 18, "bold")

# -- Helpers ------------------------------------------------------------------
def _noop():
    """Module-level no-op used to replace save_data_plot on Plotter instances.
    Must be at module scope so pickle can serialise the object."""
    pass

def style_widget(w, **kw):
    """Apply common dark-theme defaults then override with kw."""
    defaults = dict(bg=PANEL, fg=TEXT, font=FONT_B,
                    relief="flat", bd=0, highlightthickness=0)
    defaults.update(kw)
    try:
        w.configure(**defaults)
    except Exception:
        pass


def make_entry(parent, textvariable=None, width=20, **kw):
    e = tk.Entry(parent, textvariable=textvariable, width=width,
                 bg=CARD, fg=TEXT, insertbackground=TEXT,
                 relief="flat", font=FONT_B,
                 highlightthickness=1, highlightbackground=BORDER,
                 highlightcolor=ACCENT, **kw)
    return e


def make_button(parent, text, command, accent=False, small=False, **kw):
    c = ACCENT if accent else CARD
    f = FONT_S if small else FONT_B
    b = tk.Button(parent, text=text, command=command,
                  bg=c, fg=TEXT, activebackground=ACCENT2,
                  activeforeground=TEXT, relief="flat", font=f,
                  cursor="hand2", padx=12, pady=6, **kw)
    b.bind("<Enter>", lambda e: b.configure(bg=ACCENT2 if accent else BORDER))
    b.bind("<Leave>", lambda e: b.configure(bg=c))
    return b


def make_label(parent, text, big=False, dim=False, **kw):
    f = FONT_L if big else FONT_B
    c = TEXT_DIM if dim else TEXT
    return tk.Label(parent, text=text, bg=PANEL, fg=c, font=f, **kw)


def section_label(parent, text):
    frm = tk.Frame(parent, bg=PANEL)
    tk.Label(frm, text=text, bg=PANEL, fg=ACCENT, font=FONT_H).pack(side="left")
    tk.Frame(frm, bg=BORDER, height=1).pack(side="left", fill="x", expand=True, padx=(8, 0))
    return frm


def scrollable_frame(parent):
    """Returns (outer_frame, inner_frame) - pack/grid outer, add widgets to inner."""
    outer = tk.Frame(parent, bg=PANEL)
    canvas = tk.Canvas(outer, bg=PANEL, highlightthickness=0)
    sb = tk.Scrollbar(outer, orient="vertical", command=canvas.yview,
                      bg=PANEL, troughcolor=BG, activebackground=ACCENT)
    inner = tk.Frame(canvas, bg=PANEL)
    inner.bind("<Configure>",
               lambda e: canvas.configure(scrollregion=canvas.bbox("all")))
    canvas.create_window((0, 0), window=inner, anchor="nw")
    canvas.configure(yscrollcommand=sb.set)
    canvas.pack(side="left", fill="both", expand=True)
    sb.pack(side="right", fill="y")

    def _on_mousewheel(event):
        canvas.yview_scroll(int(-1 * (event.delta / 120)), "units")
    canvas.bind_all("<MouseWheel>", _on_mousewheel)
    return outer, inner


# -- mat helper (mirrors PlotterClass) ----------------------------------------
def mat_struct_to_dataframe(path: str, file: str) -> pd.DataFrame:
    mat = loadmat(os.path.join(path, file), squeeze_me=True)
    columns = {}
    for key, value in mat.items():
        if key.startswith("__"):
            continue
        if not isinstance(value, np.ndarray):
            continue
        if not np.issubdtype(value.dtype, np.floating):
            continue
        columns[key] = value.flatten()
    if not columns:
        raise ValueError("No double vector fields found in the .mat file.")
    lengths = {n: a.size for n, a in columns.items()}
    if len(set(lengths.values())) > 1:
        raise ValueError(f"Mismatched field lengths: {lengths}")
    return pd.DataFrame(columns)


def load_file(path: str, file: str) -> pd.DataFrame:
    if file.endswith('.xlsx'):
        return pd.read_excel(os.path.join(path, file))
    elif file.endswith('.csv'):
        return pd.read_csv(os.path.join(path, file))
    elif file.endswith('.mat'):
        return mat_struct_to_dataframe(path, file)
    raise ValueError(f"Unsupported file type: {file}")


# ============================================================================
# WINDOW 1 - Mode Selection
# ============================================================================
class Window1_ModeSelect(tk.Tk):
    MODES = [
        ("plot_pickle",      "[PKL]  Plot from Pickle",   "Replot a previously saved plot configuration"),
        ("plot_single_axis", "[Y1]   Single Axis Plot",   "Plot one or more signals on a shared Y-axis"),
        ("plot_twin_axes",   "[Y2]   Twin Axes Plot",     "Plot signals on two independent Y-axes"),
        ("plot_bode",        "[FFT]  Bode Plot",          "Frequency-domain magnitude & phase from chirp data"),
    ]

    def __init__(self):
        super().__init__()
        self.title("Plotter")
        self.configure(bg=BG)
        self.resizable(False, False)
        self._mode = tk.StringVar(value="plot_single_axis")
        self._build()
        self.eval('tk::PlaceWindow . center')

    def _build(self):
        # Header
        hdr = tk.Frame(self, bg=ACCENT, pady=16)
        hdr.pack(fill="x")
        tk.Label(hdr, text="PYTHON PLOTTER", bg=ACCENT, fg=BG,
                 font=("Courier New", 22, "bold")).pack()
        tk.Label(hdr, text="quickly visualize data in python",
                 bg=ACCENT, fg=BG, font=FONT_S).pack()

        body = tk.Frame(self, bg=BG, padx=32, pady=24)
        body.pack(fill="both")

        tk.Label(body, text="SELECT PLOT MODE", bg=BG, fg=TEXT_DIM,
                 font=FONT_H).pack(anchor="w", pady=(0, 12))

        for val, title, desc in self.MODES:
            card = tk.Frame(body, bg=PANEL, pady=10, padx=14,
                            highlightthickness=1, highlightbackground=BORDER,
                            cursor="hand2")
            card.pack(fill="x", pady=5)

            rb = tk.Radiobutton(card, variable=self._mode, value=val,
                                bg=PANEL, activebackground=PANEL,
                                selectcolor=BG, fg=ACCENT,
                                highlightthickness=0)
            rb.pack(side="left")

            tk.Label(card, text=title, bg=PANEL, fg=TEXT,
                     font=FONT_H).pack(side="left", padx=4)
            tk.Label(card, text=desc, bg=PANEL, fg=TEXT_DIM,
                     font=FONT_S).pack(side="left", padx=8)

            card.bind("<Button-1>", lambda e, v=val: self._mode.set(v))
            for child in card.winfo_children():
                child.bind("<Button-1>", lambda e, v=val: self._mode.set(v))

        make_button(body, "CONTINUE  >>", self._continue,
                    accent=True).pack(pady=(20, 0), fill="x")

    def _continue(self):
        mode = self._mode.get()
        self.destroy()
        Window2_FileSelect(mode).mainloop()


# ============================================================================
# WINDOW 2 - Folder + File Selection
# ============================================================================
class Window2_FileSelect(tk.Tk):
    def __init__(self, mode: str):
        super().__init__()
        self.mode = mode
        self.title("Plotter - Select Data Files")
        self.configure(bg=BG)
        self.geometry("640x560")
        self._folder = tk.StringVar()
        self._file_vars = {}   # filename -> BooleanVar
        self._dataframes = {}
        self._build()
        self.eval('tk::PlaceWindow . center')

    def _build(self):
        # Pickle mode needs no file selection -- jump straight to config
        if self.mode == "plot_pickle":
            folder = filedialog.askdirectory(title="Select folder containing 'Pickles' subfolder")
            self.destroy()
            Window3_Config("plot_pickle", folder or "", {}, {}).mainloop()
            return

        hdr = tk.Frame(self, bg=PANEL, pady=12, padx=20)
        hdr.pack(fill="x")
        tk.Label(hdr, text=f"MODE: {self.mode.replace('_',' ').upper()}",
                 bg=PANEL, fg=ACCENT, font=FONT_H).pack(anchor="w")
        tk.Label(hdr, text="Step 1 of 2  -  Choose data folder & files",
                 bg=PANEL, fg=TEXT_DIM, font=FONT_S).pack(anchor="w")

        body = tk.Frame(self, bg=BG, padx=28, pady=20)
        body.pack(fill="both", expand=True)

        # Folder row
        tk.Label(body, text="DATA FOLDER", bg=BG, fg=TEXT_DIM,
                 font=FONT_H).pack(anchor="w")
        row = tk.Frame(body, bg=BG)
        row.pack(fill="x", pady=(4, 16))
        e = make_entry(row, textvariable=self._folder, width=46)
        e.pack(side="left", padx=(0, 8))
        make_button(row, "Browse", self._browse).pack(side="left")

        # File list area
        tk.Label(body, text="SELECT FILES TO PLOT", bg=BG, fg=TEXT_DIM,
                 font=FONT_H).pack(anchor="w")
        tk.Label(body, text="(check all files you want to include)",
                 bg=BG, fg=TEXT_DIM, font=FONT_S).pack(anchor="w", pady=(0, 6))

        list_outer, self._list_inner = scrollable_frame(body)
        list_outer.pack(fill="both", expand=True)

        self._empty_lbl = tk.Label(self._list_inner,
                                   text="??? Browse to a folder to list files",
                                   bg=PANEL, fg=TEXT_DIM, font=FONT_S, pady=16)
        self._empty_lbl.pack(fill="x")

        make_button(body, "CONTINUE  >>", self._continue,
                    accent=True).pack(pady=(16, 0), fill="x")

    def _browse(self):
        folder = filedialog.askdirectory(title="Select data folder")
        if not folder:
            return
        self._folder.set(folder)
        self._populate_files(folder)

    def _populate_files(self, folder):
        for w in self._list_inner.winfo_children():
            w.destroy()
        self._file_vars.clear()

        files = [f for f in os.listdir(folder)
                 if f.endswith(('.xlsx', '.csv', '.mat'))]

        if not files:
            tk.Label(self._list_inner, text="No .xlsx / .csv / .mat files found.",
                     bg=PANEL, fg=ACCENT2, font=FONT_S, pady=12).pack(fill="x")
            return

        for f in sorted(files):
            var = tk.BooleanVar(value=False)
            self._file_vars[f] = var
            row = tk.Frame(self._list_inner, bg=PANEL, pady=4, padx=10)
            row.pack(fill="x")
            cb = tk.Checkbutton(row, variable=var, bg=PANEL,
                                activebackground=PANEL, selectcolor=BG,
                                fg=ACCENT, highlightthickness=0)
            cb.pack(side="left")
            tk.Label(row, text=f, bg=PANEL, fg=TEXT, font=FONT_B).pack(side="left")

    def _continue(self):
        folder = self._folder.get().strip()
        if not folder or not os.path.isdir(folder):
            messagebox.showerror("Error", "Please select a valid folder.")
            return

        selected = [f for f, v in self._file_vars.items() if v.get()]

        if not selected:
            messagebox.showerror("Error", "Please select at least one file.")
            return

        # Load dataframes
        dfs = {}
        for f in selected:
            try:
                dfs[f] = load_file(folder, f)
            except Exception as ex:
                messagebox.showerror("Load Error", f"Could not load {f}:\n{ex}")
                return

        self.destroy()
        Window3_Config(self.mode, folder, selected, dfs).mainloop()


# ============================================================================
# WINDOW 3 - Column Selection + Plot Config
# ============================================================================
class Window3_Config(tk.Tk):
    def __init__(self, mode: str, folder: str,
                 selected_files: list, dataframes: dict):
        super().__init__()
        self.mode = mode
        self.folder = folder
        self.selected_files = selected_files
        self.dataframes = dataframes

        self.title("Plotter - Configure Plot")
        self.configure(bg=BG)
        self.geometry("820x780")
        self.eval('tk::PlaceWindow . center')

        # -- shared state --
        self._plotstyle   = tk.StringVar(value="seaborn-talk")
        self._title       = tk.StringVar(value="")
        self._xlabel      = tk.StringVar(value="")
        self._ylabel1     = tk.StringVar(value="")
        self._ylabel2     = tk.StringVar(value="")
        self._xlim_lo     = tk.StringVar(value="")
        self._xlim_hi     = tk.StringVar(value="")
        self._ylim1_lo    = tk.StringVar(value="")
        self._ylim1_hi    = tk.StringVar(value="")
        self._ylim2_lo    = tk.StringVar(value="")
        self._ylim2_hi    = tk.StringVar(value="")
        self._legend      = tk.BooleanVar(value=True)
        self._verbose     = tk.BooleanVar(value=False)
        self._figw        = tk.StringVar(value="10")
        self._figh        = tk.StringVar(value="6")
        self._title_fs    = tk.StringVar(value="")
        self._label_fs    = tk.StringVar(value="")
        self._tick_fs     = tk.StringVar(value="")
        self._legend_fs   = tk.StringVar(value="")

        # save options
        self._save_pickle  = tk.BooleanVar(value=False)
        self._pickle_name  = tk.StringVar(value="")
        self._save_png     = tk.BooleanVar(value=False)
        self._png_name     = tk.StringVar(value="")

        # bode-specific
        self._start_freq  = tk.StringVar(value="50")
        self._end_freq    = tk.StringVar(value="200")
        self._sample_rate = tk.StringVar(value="10000")

        # column selection data (built dynamically)
        # x_selections[file] = column StringVar
        # y_selections[file] = list of {col: StringVar, label: StringVar, axis: IntVar}
        # For bode: input_selections[file][y_col_var] = StringVar for input col
        self._x_file      = tk.StringVar()
        self._x_col       = tk.StringVar()
        self._y_rows      = {}   # file -> list of row-dicts
        self._bode_inputs = {}   # file -> list of input StringVars (parallel to _y_rows)

        self._build()

    # -- Top-level layout ----------------------------------------------------
    def _build(self):
        # Header strip
        hdr = tk.Frame(self, bg=PANEL, pady=12, padx=20)
        hdr.pack(fill="x")
        tk.Label(hdr, text=f"MODE: {self.mode.replace('_',' ').upper()}",
                 bg=PANEL, fg=ACCENT, font=FONT_H).pack(anchor="w")
        tk.Label(hdr, text="Step 2 of 2  -  Configure columns & plot properties",
                 bg=PANEL, fg=TEXT_DIM, font=FONT_S).pack(anchor="w")

        # Main scrollable body
        outer, body = scrollable_frame(self)
        outer.pack(fill="both", expand=True, padx=0, pady=0)
        body.configure(padx=28, pady=16)

        if self.mode == "plot_pickle":
            self._build_pickle_section(body)
        else:
            if self.mode != "plot_bode":
                self._build_x_section(body)
            self._build_y_section(body)
            if self.mode == "plot_bode":
                self._build_bode_params(body)

        self._build_props_section(body)

        # Footer button
        foot = tk.Frame(self, bg=BG, pady=12, padx=28)
        foot.pack(fill="x", side="bottom")
        make_button(foot, ">>  GENERATE PLOT", self._run,
                    accent=True).pack(fill="x")

    # -- Pickle section -------------------------------------------------------
    def _build_pickle_section(self, body):
        section_label(body, "PICKLE FILE").pack(fill="x", pady=(0, 10))
        tk.Label(body, text="Pickle files are loaded from the 'Pickles' subfolder inside your data folder.",
                 bg=PANEL, fg=TEXT_DIM, font=FONT_S, wraplength=700,
                 justify="left").pack(anchor="w", pady=(0, 8))

        pdir = os.path.join(self.folder, "Pickles")
        if os.path.isdir(pdir):
            pickles = [f for f in os.listdir(pdir) if f.endswith('.pkl')]
        else:
            pickles = []

        # _pickle_label_vars: {file: [ {col, axis(opt), label_var}, ... ]}
        # populated by _on_pickle_select whenever the selection changes
        self._pickle_label_vars = {}

        self._pickle_var = tk.StringVar()
        if pickles:
            self._pickle_var.set(pickles[0])
            for p in pickles:
                rb = tk.Radiobutton(body, text=p, variable=self._pickle_var,
                                    value=p, bg=PANEL, fg=TEXT,
                                    selectcolor=BG, activebackground=PANEL,
                                    font=FONT_B, highlightthickness=0,
                                    command=self._on_pickle_select)
                rb.pack(anchor="w")

            # Container for the editable-labels panel (rebuilt on each selection)
            self._pickle_labels_frame = tk.Frame(body, bg=PANEL)
            self._pickle_labels_frame.pack(fill="x", pady=(12, 0))

            # Show labels for the initially-selected pickle straight away
            self._on_pickle_select()
        else:
            tk.Label(body, text="[!] No pickle files found in 'Pickles' subfolder.",
                     bg=PANEL, fg=ACCENT2, font=FONT_B).pack(anchor="w")

    def _on_pickle_select(self):
        """Load the selected pickle and rebuild the editable label rows."""
        # Clear previous contents
        for w in self._pickle_labels_frame.winfo_children():
            w.destroy()
        self._pickle_label_vars = {}

        pkl_name = self._pickle_var.get()
        if not pkl_name:
            return

        pkl_path = os.path.join(self.folder, "Pickles", pkl_name)
        try:
            with open(pkl_path, "rb") as f:
                obj = pickle.load(f)
        except Exception as ex:
            tk.Label(self._pickle_labels_frame,
                     text=f"[!] Could not load pickle: {ex}",
                     bg=PANEL, fg=ACCENT2, font=FONT_S).pack(anchor="w")
            return

        columns = getattr(obj, "columns", None)
        plot_type = getattr(obj, "plot_type", "unknown")

        if not columns:
            tk.Label(self._pickle_labels_frame,
                     text="(No column data found in this pickle.)",
                     bg=PANEL, fg=TEXT_DIM, font=FONT_S).pack(anchor="w")
            return

        section_label(self._pickle_labels_frame,
                      "COLUMN LABELS  (editable)").pack(fill="x", pady=(0, 8))

        for fname, col_tuples in columns.items():
            # File header
            tk.Label(self._pickle_labels_frame, text=fname,
                     bg=PANEL, fg=ACCENT, font=FONT_H).pack(anchor="w", pady=(4, 2))

            file_rows = []
            for entry in col_tuples:
                # Unpack regardless of tuple length (single/bode vs twin)
                if plot_type == "twin_axes":
                    col, axis, label = entry
                else:
                    col, label = entry
                    axis = None

                row = tk.Frame(self._pickle_labels_frame, bg=PANEL)
                row.pack(fill="x", pady=2)

                # Column name (read-only display)
                col_display = f"{col}"
                if axis is not None:
                    col_display += f"  [axis {axis}]"
                tk.Label(row, text=col_display, bg=PANEL, fg=TEXT,
                         font=FONT_B, width=28, anchor="w").pack(side="left")

                tk.Label(row, text="Label:", bg=PANEL, fg=TEXT_DIM,
                         font=FONT_S).pack(side="left", padx=(8, 4))

                label_var = tk.StringVar(value=label)
                make_entry(row, textvariable=label_var, width=22).pack(side="left")

                file_rows.append({"col": col, "axis": axis, "label_var": label_var})

            self._pickle_label_vars[fname] = file_rows

    # -- X-axis section -------------------------------------------------------
    def _build_x_section(self, body):
        section_label(body, "X-AXIS").pack(fill="x", pady=(0, 10))

        row = tk.Frame(body, bg=PANEL)
        row.pack(fill="x", pady=(0, 4))
        tk.Label(row, text="Source file:", bg=PANEL, fg=TEXT_DIM,
                 font=FONT_S, width=14, anchor="w").pack(side="left")

        file_opts = self.selected_files if self.selected_files else ["(none)"]
        self._x_file.set(file_opts[0])
        om_file = tk.OptionMenu(row, self._x_file, *file_opts,
                                command=self._on_x_file_change)
        om_file.configure(bg=CARD, fg=TEXT, font=FONT_B,
                          activebackground=BORDER, highlightthickness=0, relief="flat")
        om_file["menu"].configure(bg=CARD, fg=TEXT, font=FONT_B)
        om_file.pack(side="left")

        row2 = tk.Frame(body, bg=PANEL)
        row2.pack(fill="x", pady=(0, 16))
        tk.Label(row2, text="Column:", bg=PANEL, fg=TEXT_DIM,
                 font=FONT_S, width=14, anchor="w").pack(side="left")
        self._x_col_menu_frame = tk.Frame(row2, bg=PANEL)
        self._x_col_menu_frame.pack(side="left")
        self._refresh_x_col_menu()

    def _on_x_file_change(self, val):
        self._refresh_x_col_menu()

    def _refresh_x_col_menu(self):
        for w in self._x_col_menu_frame.winfo_children():
            w.destroy()
        fname = self._x_file.get()
        if fname in self.dataframes:
            cols = list(self.dataframes[fname].columns)
            self._x_col.set(cols[0])
            om = tk.OptionMenu(self._x_col_menu_frame, self._x_col, *cols)
            om.configure(bg=CARD, fg=TEXT, font=FONT_B,
                         activebackground=BORDER, highlightthickness=0, relief="flat")
            om["menu"].configure(bg=CARD, fg=TEXT, font=FONT_B)
            om.pack()

    # -- Y-axis / signal section ----------------------------------------------
    def _build_y_section(self, body):
        is_bode = self.mode == "plot_bode"
        lbl = "INPUT / OUTPUT SIGNALS" if is_bode else "Y-AXIS SIGNALS"
        section_label(body, lbl).pack(fill="x", pady=(8, 10))

        for fname in self.selected_files:
            df = self.dataframes[fname]
            cols = list(df.columns)
            self._y_rows[fname] = []
            if is_bode:
                self._bode_inputs[fname] = []

            # Per-file card
            card = tk.Frame(body, bg=CARD, padx=12, pady=10,
                            highlightthickness=1, highlightbackground=BORDER)
            card.pack(fill="x", pady=6)

            tk.Label(card, text=fname, bg=CARD, fg=ACCENT,
                     font=FONT_H).pack(anchor="w", pady=(0, 6))

            rows_frame = tk.Frame(card, bg=CARD)
            rows_frame.pack(fill="x")

            # store ref so we can add rows
            card._rows_frame = rows_frame
            card._fname      = fname
            card._cols       = cols
            card._is_bode    = is_bode

            self._add_y_row(card)

            make_button(card, "+  Add Signal", lambda c=card: self._add_y_row(c),
                        small=True).pack(anchor="w", pady=(6, 0))

    def _add_y_row(self, card):
        fname  = card._fname
        cols   = card._cols
        is_bode = card._is_bode
        rf     = card._rows_frame

        row_bg = CARD
        row = tk.Frame(rf, bg=row_bg, pady=4)
        row.pack(fill="x")

        col_var   = tk.StringVar(value=cols[0])
        label_var = tk.StringVar(value="")

        if is_bode:
            # Output col
            tk.Label(row, text="Output col:", bg=row_bg, fg=TEXT_DIM,
                     font=FONT_S, width=10, anchor="w").grid(row=0, column=0, sticky="w")
            om = tk.OptionMenu(row, col_var, *cols)
            om.configure(bg=BG, fg=TEXT, font=FONT_S,
                         activebackground=BORDER, highlightthickness=0, relief="flat")
            om["menu"].configure(bg=BG, fg=TEXT, font=FONT_S)
            om.grid(row=0, column=1, sticky="w", padx=(0, 8))

            # Input col
            input_var = tk.StringVar(value=cols[0])
            tk.Label(row, text="Input col:", bg=row_bg, fg=TEXT_DIM,
                     font=FONT_S, width=9, anchor="w").grid(row=0, column=2, sticky="w")
            om2 = tk.OptionMenu(row, input_var, *cols)
            om2.configure(bg=BG, fg=TEXT, font=FONT_S,
                          activebackground=BORDER, highlightthickness=0, relief="flat")
            om2["menu"].configure(bg=BG, fg=TEXT, font=FONT_S)
            om2.grid(row=0, column=3, sticky="w", padx=(0, 8))

            # Label
            tk.Label(row, text="Label:", bg=row_bg, fg=TEXT_DIM,
                     font=FONT_S, width=6, anchor="w").grid(row=0, column=4, sticky="w")
            e = make_entry(row, textvariable=label_var, width=14)
            e.grid(row=0, column=5, sticky="w", padx=(0, 6))

            row_dict = {"col": col_var, "label": label_var, "input": input_var}
            self._y_rows[fname].append(row_dict)

        elif self.mode == "plot_twin_axes":
            axis_var = tk.IntVar(value=1)

            tk.Label(row, text="Column:", bg=row_bg, fg=TEXT_DIM,
                     font=FONT_S, width=8, anchor="w").grid(row=0, column=0, sticky="w")
            om = tk.OptionMenu(row, col_var, *cols)
            om.configure(bg=BG, fg=TEXT, font=FONT_S,
                         activebackground=BORDER, highlightthickness=0, relief="flat")
            om["menu"].configure(bg=BG, fg=TEXT, font=FONT_S)
            om.grid(row=0, column=1, sticky="w", padx=(0, 8))

            tk.Label(row, text="Label:", bg=row_bg, fg=TEXT_DIM,
                     font=FONT_S, width=6, anchor="w").grid(row=0, column=2, sticky="w")
            make_entry(row, textvariable=label_var, width=14).grid(row=0, column=3, padx=(0, 8))

            tk.Label(row, text="Axis:", bg=row_bg, fg=TEXT_DIM,
                     font=FONT_S).grid(row=0, column=4, sticky="w")
            for val, txt in [(1, "Left (1)"), (2, "Right (2)")]:
                tk.Radiobutton(row, text=txt, variable=axis_var, value=val,
                               bg=row_bg, fg=TEXT, selectcolor=BG,
                               activebackground=row_bg, font=FONT_S,
                               highlightthickness=0).grid(row=0, column=4+val, sticky="w", padx=2)

            row_dict = {"col": col_var, "label": label_var, "axis": axis_var}
            self._y_rows[fname].append(row_dict)

        else:  # single axis
            tk.Label(row, text="Column:", bg=row_bg, fg=TEXT_DIM,
                     font=FONT_S, width=8, anchor="w").grid(row=0, column=0, sticky="w")
            om = tk.OptionMenu(row, col_var, *cols)
            om.configure(bg=BG, fg=TEXT, font=FONT_S,
                         activebackground=BORDER, highlightthickness=0, relief="flat")
            om["menu"].configure(bg=BG, fg=TEXT, font=FONT_S)
            om.grid(row=0, column=1, sticky="w", padx=(0, 8))

            tk.Label(row, text="Label:", bg=row_bg, fg=TEXT_DIM,
                     font=FONT_S, width=6, anchor="w").grid(row=0, column=2, sticky="w")
            make_entry(row, textvariable=label_var, width=18).grid(row=0, column=3)

            row_dict = {"col": col_var, "label": label_var}
            self._y_rows[fname].append(row_dict)

    # -- Bode params ----------------------------------------------------------
    def _build_bode_params(self, body):
        section_label(body, "BODE PARAMETERS").pack(fill="x", pady=(12, 8))
        grid = tk.Frame(body, bg=PANEL)
        grid.pack(anchor="w")
        for col_i, (lbl, var) in enumerate([
                ("Start Freq (Hz)", self._start_freq),
                ("End Freq (Hz)",   self._end_freq),
                ("Sampling Rate (Hz)", self._sample_rate)]):
            tk.Label(grid, text=lbl, bg=PANEL, fg=TEXT_DIM,
                     font=FONT_S).grid(row=0, column=col_i*2, sticky="w", padx=(0, 4), pady=2)
            make_entry(grid, textvariable=var, width=10).grid(row=0, column=col_i*2+1, padx=(0, 16))

    # -- Plot properties section ----------------------------------------------
    def _build_props_section(self, body):
        section_label(body, "PLOT PROPERTIES").pack(fill="x", pady=(16, 10))

        outer = tk.Frame(body, bg=PANEL)
        outer.pack(fill="x")

        def row_pair(parent, r, label, var, width=18):
            tk.Label(parent, text=label, bg=PANEL, fg=TEXT_DIM,
                     font=FONT_S, width=14, anchor="w").grid(row=r, column=0, sticky="w", pady=3)
            make_entry(parent, textvariable=var, width=width).grid(row=r, column=1, sticky="w")

        # Style
        tk.Label(outer, text="Plot Style", bg=PANEL, fg=TEXT_DIM,
                 font=FONT_S, width=14, anchor="w").grid(row=0, column=0, sticky="w", pady=3)
        styles = ["seaborn-talk", "science", "science-ieee"]
        om = tk.OptionMenu(outer, self._plotstyle, *styles)
        om.configure(bg=CARD, fg=TEXT, font=FONT_S,
                     activebackground=BORDER, highlightthickness=0, relief="flat")
        om["menu"].configure(bg=CARD, fg=TEXT, font=FONT_S)
        om.grid(row=0, column=1, sticky="w")

        row_pair(outer, 1, "Title",   self._title)
        row_pair(outer, 2, "X Label", self._xlabel)
        row_pair(outer, 3, "Y Label 1", self._ylabel1)
        if self.mode in ("plot_twin_axes",):
            row_pair(outer, 4, "Y Label 2", self._ylabel2)

        # Limits
        tk.Label(outer, text="X Limits", bg=PANEL, fg=TEXT_DIM,
                 font=FONT_S, width=14, anchor="w").grid(row=10, column=0, sticky="w", pady=(10, 3))
        lim_row = tk.Frame(outer, bg=PANEL)
        lim_row.grid(row=10, column=1, sticky="w")
        make_entry(lim_row, textvariable=self._xlim_lo, width=8).pack(side="left")
        tk.Label(lim_row, text=" to ", bg=PANEL, fg=TEXT_DIM, font=FONT_S).pack(side="left")
        make_entry(lim_row, textvariable=self._xlim_hi, width=8).pack(side="left")
        tk.Label(lim_row, text="  (leave blank for auto)", bg=PANEL, fg=TEXT_DIM, font=FONT_S).pack(side="left")

        tk.Label(outer, text="Y1 Limits", bg=PANEL, fg=TEXT_DIM,
                 font=FONT_S, width=14, anchor="w").grid(row=11, column=0, sticky="w", pady=3)
        lim_row2 = tk.Frame(outer, bg=PANEL)
        lim_row2.grid(row=11, column=1, sticky="w")
        make_entry(lim_row2, textvariable=self._ylim1_lo, width=8).pack(side="left")
        tk.Label(lim_row2, text=" to ", bg=PANEL, fg=TEXT_DIM, font=FONT_S).pack(side="left")
        make_entry(lim_row2, textvariable=self._ylim1_hi, width=8).pack(side="left")

        if self.mode in ("plot_twin_axes", "plot_bode"):
            tk.Label(outer, text="Y2 Limits", bg=PANEL, fg=TEXT_DIM,
                     font=FONT_S, width=14, anchor="w").grid(row=12, column=0, sticky="w", pady=3)
            lim_row3 = tk.Frame(outer, bg=PANEL)
            lim_row3.grid(row=12, column=1, sticky="w")
            make_entry(lim_row3, textvariable=self._ylim2_lo, width=8).pack(side="left")
            tk.Label(lim_row3, text=" to ", bg=PANEL, fg=TEXT_DIM, font=FONT_S).pack(side="left")
            make_entry(lim_row3, textvariable=self._ylim2_hi, width=8).pack(side="left")

        # Figure size + font sizes
        section_label(body, "FIGURE & FONT SIZES (leave blank for defaults)").pack(fill="x", pady=(16, 8))
        sz = tk.Frame(body, bg=PANEL)
        sz.pack(anchor="w")

        for ci, (lbl, var) in enumerate([
                ("Fig Width",  self._figw),
                ("Fig Height", self._figh),
                ("Title FS",   self._title_fs),
                ("Label FS",   self._label_fs),
                ("Tick FS",    self._tick_fs),
                ("Legend FS",  self._legend_fs)]):
            tk.Label(sz, text=lbl, bg=PANEL, fg=TEXT_DIM,
                     font=FONT_S).grid(row=0, column=ci*2, sticky="w", padx=(0, 4))
            make_entry(sz, textvariable=var, width=6).grid(row=0, column=ci*2+1, padx=(0, 12))

        # Legend + Verbose
        tog = tk.Frame(body, bg=PANEL, pady=8)
        tog.pack(anchor="w")
        for var, lbl in [(self._legend, "Show Legend"), (self._verbose, "Verbose Output")]:
            tk.Checkbutton(tog, text=lbl, variable=var,
                           bg=PANEL, fg=TEXT, selectcolor=BG,
                           activebackground=PANEL, font=FONT_B,
                           highlightthickness=0).pack(side="left", padx=(0, 20))

        # Save options
        section_label(body, "SAVE OPTIONS").pack(fill="x", pady=(16, 8))

        # Pickle save
        pkl_row = tk.Frame(body, bg=PANEL)
        pkl_row.pack(anchor="w", pady=(0, 4))
        tk.Checkbutton(pkl_row, text="Save settings as pickle",
                       variable=self._save_pickle,
                       bg=PANEL, fg=TEXT, selectcolor=BG,
                       activebackground=PANEL, font=FONT_B,
                       highlightthickness=0,
                       command=self._toggle_pickle_name).pack(side="left")
        self._pkl_name_entry = make_entry(pkl_row, textvariable=self._pickle_name, width=24)
        self._pkl_name_entry.pack(side="left", padx=(10, 0))
        self._pkl_name_entry.configure(state="disabled")
        tk.Label(pkl_row, text="(no spaces)", bg=PANEL, fg=TEXT_DIM,
                 font=FONT_S).pack(side="left", padx=(6, 0))

        # PNG save
        png_row = tk.Frame(body, bg=PANEL)
        png_row.pack(anchor="w", pady=(4, 0))
        tk.Checkbutton(png_row, text="Save plot as PNG",
                       variable=self._save_png,
                       bg=PANEL, fg=TEXT, selectcolor=BG,
                       activebackground=PANEL, font=FONT_B,
                       highlightthickness=0,
                       command=self._toggle_png_name).pack(side="left")
        self._png_name_entry = make_entry(png_row, textvariable=self._png_name, width=24)
        self._png_name_entry.pack(side="left", padx=(10, 0))
        self._png_name_entry.configure(state="disabled")
        tk.Label(png_row, text="(blank = use plot title)",
                 bg=PANEL, fg=TEXT_DIM, font=FONT_S).pack(side="left", padx=(6, 0))

    # -- Toggle helpers for save entries --------------------------------------
    def _toggle_pickle_name(self):
        state = "normal" if self._save_pickle.get() else "disabled"
        self._pkl_name_entry.configure(state=state)

    def _toggle_png_name(self):
        state = "normal" if self._save_png.get() else "disabled"
        self._png_name_entry.configure(state=state)

    # -- Parse helpers --------------------------------------------------------
    def _parse_float(self, s, default=False):
        s = s.strip()
        if not s:
            return default
        try:
            return float(s)
        except ValueError:
            return default

    def _parse_limits(self, lo_var, hi_var):
        lo = self._parse_float(lo_var.get())
        hi = self._parse_float(hi_var.get())
        if lo is False or hi is False:
            return False
        return (lo, hi)

    def _parse_fontsize(self, var):
        v = self._parse_float(var.get())
        return int(v) if v is not False else False

    # -- GUI-driven save (replaces save_data_plot input() prompts) ------------
    def _gui_save(self, plotter, fig=None):
        """Save pickle and/or PNG. fig must be the fully-drawn Figure object.
        PNG is saved immediately from the figure; pickle serialises the plotter state."""

        # Pickle save -- no figure needed, order doesn't matter
        if self._save_pickle.get():
            pkl_name = self._pickle_name.get().strip()
            if not pkl_name:
                messagebox.showwarning("Pickle Save", "Enter a filename for the pickle.")
            else:
                pkl_dir = os.path.join(self.folder, "Pickles")
                os.makedirs(pkl_dir, exist_ok=True)
                pkl_path = os.path.join(pkl_dir, pkl_name + ".pkl")
                with open(pkl_path, "wb") as f:
                    pickle.dump(plotter, f)
                print(f"Settings pickled to: {pkl_path}")

        # PNG save -- must happen BEFORE plt.show() while the figure is populated
        if self._save_png.get():
            if fig is None:
                fig = plt.gcf()
            png_name = self._png_name.get().strip()
            if not png_name:
                png_name = plotter.title if plotter.title else "plot"
            png_dir = os.path.join(self.folder, "Plots")
            os.makedirs(png_dir, exist_ok=True)
            png_path = os.path.join(png_dir, png_name + ".png")
            fig.savefig(png_path, bbox_inches="tight", dpi=300)
            print(f"Plot saved to: {png_path}")

    # -- Run ------------------------------------------------------------------
    def _run(self):
        try:
            self._do_run()
        except Exception as ex:
            messagebox.showerror("Error", str(ex))
            import traceback; traceback.print_exc()

    def _do_run(self):
        # Build shared Plotter kwargs
        figw = self._parse_float(self._figw.get(), 10)
        figh = self._parse_float(self._figh.get(), 6)
        figsize = (figw, figh)

        kwargs = dict(
            foldername      = self.folder,
            plotstyle       = self._plotstyle.get(),
            verbose         = self._verbose.get(),
            title           = self._title.get().strip() or False,
            xlabel          = self._xlabel.get().strip(),
            ylabel1         = self._ylabel1.get().strip(),
            ylabel2         = self._ylabel2.get().strip(),
            xlimits         = self._parse_limits(self._xlim_lo, self._xlim_hi),
            ylimits1        = self._parse_limits(self._ylim1_lo, self._ylim1_hi),
            ylimits2        = self._parse_limits(self._ylim2_lo, self._ylim2_hi),
            legend          = self._legend.get(),
            figsize         = figsize,
            title_fontsize  = self._parse_fontsize(self._title_fs),
            label_fontsize  = self._parse_fontsize(self._label_fs),
            tick_fontsize   = self._parse_fontsize(self._tick_fs),
            legend_fontsize = self._parse_fontsize(self._legend_fs),
        )

        from PlotterClass import Plotter
        plotter = Plotter(**kwargs)

        # ── Pickle mode: load pkl, patch display settings, plot ──────────────
        if self.mode == "plot_pickle":
            pkl_name = self._pickle_var.get()
            if not pkl_name:
                messagebox.showerror("Error", "No pickle file selected.")
                return
            pkl_path = os.path.join(self.folder, "Pickles", pkl_name)
            with open(pkl_path, "rb") as f:
                plotpickle = pickle.load(f)

            # Patch all display settings from current GUI values
            plotpickle.foldername      = self.folder
            plotpickle.plotstyle       = plotter.plotstyle
            plotpickle.verbose         = plotter.verbose
            plotpickle.title           = plotter.title
            plotpickle.xlabel          = plotter.xlabel
            plotpickle.ylabel1         = plotter.ylabel1
            plotpickle.ylabel2         = plotter.ylabel2
            plotpickle.xlimits         = plotter.xlimits
            plotpickle.ylimits1        = plotter.ylimits1
            plotpickle.ylimits2        = plotter.ylimits2
            plotpickle.legend          = plotter.legend
            plotpickle.figsize         = plotter.figsize
            plotpickle.title_fontsize  = plotter.title_fontsize
            plotpickle.label_fontsize  = plotter.label_fontsize
            plotpickle.tick_fontsize   = plotter.tick_fontsize
            plotpickle.legend_fontsize = plotter.legend_fontsize

            # Apply any edited labels from the GUI back onto the loaded object
            if self._pickle_label_vars:
                new_columns = {}
                for fname, rows in self._pickle_label_vars.items():
                    tuples = []
                    for rd in rows:
                        col   = rd["col"]
                        axis  = rd["axis"]
                        label = rd["label_var"].get().strip() or col
                        if axis is not None:          # twin axes
                            tuples.append((col, axis, label))
                        else:                         # single axis / bode
                            tuples.append((col, label))
                    new_columns[fname] = tuple(tuples)
                plotpickle.columns = new_columns

            # Call plot_data directly (bypasses save_data_plot prompts)
            plotpickle.save_data_plot = _noop  # handled by _gui_save
            plotpickle.plot_data()
            fig = plt.gcf()           # capture the fully-drawn figure
            self._gui_save(plotpickle, fig=fig)   # save BEFORE show
            plt.show()
            return

        # ── Inject data into plotter (bypass select_data prompts) ────────────
        plotter.dataframes     = self.dataframes
        plotter.selected_files = self.selected_files

        if self.mode == "plot_single_axis":
            plotter.plot_type = "single_axis"

            x_file = self._x_file.get()
            x_col  = self._x_col.get()
            plotter.x_data        = x_col
            plotter.x_data_values = np.array(self.dataframes[x_file][x_col])

            columns = {}
            for fname, rows in self._y_rows.items():
                tuples = []
                for rd in rows:
                    col = rd["col"].get()
                    lbl = rd["label"].get().strip() or col
                    tuples.append((col, lbl))
                columns[fname] = tuple(tuples)
            plotter.columns = columns
            plotter.save_data_plot = _noop  # handled by _gui_save
            plotter.plot_data()
            fig = plt.gcf()                  # capture fully-drawn figure
            self._gui_save(plotter, fig=fig) # save BEFORE show
            plt.show()

        elif self.mode == "plot_twin_axes":
            plotter.plot_type = "twin_axes"

            x_file = self._x_file.get()
            x_col  = self._x_col.get()
            plotter.x_data        = x_col
            plotter.x_data_values = np.array(self.dataframes[x_file][x_col])

            columns = {}
            for fname, rows in self._y_rows.items():
                tuples = []
                for rd in rows:
                    col  = rd["col"].get()
                    lbl  = rd["label"].get().strip() or col
                    axis = rd["axis"].get()
                    tuples.append((col, axis, lbl))
                columns[fname] = tuple(tuples)
            plotter.columns = columns
            plotter.save_data_plot = _noop  # handled by _gui_save
            plotter.plot_data()
            fig = plt.gcf()                  # capture fully-drawn figure
            self._gui_save(plotter, fig=fig) # save BEFORE show
            plt.show()

        elif self.mode == "plot_bode":
            plotter.plot_type     = "bode"
            plotter.start_freq    = float(self._start_freq.get())
            plotter.end_freq      = float(self._end_freq.get())
            plotter.sampling_rate = float(self._sample_rate.get())

            pairs = []
            for fname, rows in self._y_rows.items():
                for rd in rows:
                    out_col = rd["col"].get()
                    in_col  = rd["input"].get()
                    lbl     = rd["label"].get().strip() or out_col
                    pairs.append((fname, out_col, in_col, lbl))

            if not pairs:
                messagebox.showerror("Error", "No output signals configured.")
                return

            style = plotter.plotstyle
            try:
                import scienceplots  # noqa
                if style == "science":
                    plt.style.use("science")
                elif style == "science-ieee":
                    plt.style.use(["science", "ieee"])
                else:
                    plt.style.use("seaborn-talk")
            except Exception:
                plt.style.use("seaborn-v0_8-talk")

            colors = ["tab:blue", "tab:orange", "tab:green", "tab:red",
                      "tab:purple", "tab:brown", "tab:pink", "tab:gray",
                      "tab:olive", "tab:cyan"]

            figsize = plotter.figsize or (10, 6)
            fig, (ax_mag, ax_phase) = plt.subplots(2, 1, figsize=figsize)

            for ci, (fname, out_col, in_col, lbl) in enumerate(pairs):
                df           = self.dataframes[fname]
                input_signal = np.array(df[in_col]) - np.mean(df[in_col])
                output_raw   = np.array(df[out_col])

                n    = len(input_signal)
                d    = 1.0 / plotter.sampling_rate
                freq = np.fft.rfftfreq(n, d)

                if n != len(output_raw):
                    f_i = interp1d(np.linspace(0, 1, len(output_raw)),
                                   output_raw, kind="linear",
                                   fill_value="extrapolate")
                    output_signal = f_i(np.linspace(0, 1, n)) - np.mean(output_raw)
                else:
                    output_signal = output_raw - np.mean(output_raw)

                H         = np.fft.rfft(output_signal) / np.fft.rfft(input_signal)
                magnitude = 20 * np.log10(np.abs(H))
                phase     = np.angle(H, deg=True)

                xlim = plotter.xlimits if plotter.xlimits else (plotter.start_freq, plotter.end_freq)
                ax_mag.plot(freq, magnitude, color=colors[ci % len(colors)], label=lbl)
                ax_mag.set_ylabel("Magnitude (dB)")
                ax_mag.set_xlim(xlim)
                if plotter.ylimits1:
                    ax_mag.set_ylim(plotter.ylimits1)
                ax_mag.grid(which="both", axis="both")

                ax_phase.plot(freq, phase, color=colors[ci % len(colors)], label=lbl)
                ax_phase.set_xlabel("Frequency (Hz)")
                ax_phase.set_ylabel("Phase (deg)")
                ax_phase.set_xlim(xlim)
                if plotter.ylimits2:
                    ax_phase.set_ylim(plotter.ylimits2)
                ax_phase.grid(which="both", axis="both")

            if plotter.title:
                fs = plotter.title_fontsize
                ax_mag.set_title(plotter.title, **({"fontsize": fs} if fs else {}))

            if plotter.legend:
                ax_mag.legend(fontsize=plotter.legend_fontsize or None)
                ax_phase.legend(fontsize=plotter.legend_fontsize or None)

            plt.tight_layout()
            self._gui_save(plotter, fig=fig)  # save BEFORE show
            plt.show()


# ============================================================================
# Entry Point
# ============================================================================
if __name__ == "__main__":
    Window1_ModeSelect().mainloop()
